
# *Do not manually modify this file*
#
# This file has been generated via https://github.com/mozilla/lookml-generator
# You can extend this view in the looker-spoke-default project (https://github.com/mozilla/looker-spoke-default)

view: update_table {
  dimension: additional_properties {
    sql: ${TABLE}.additional_properties ;;
    hidden: yes
    description: "A JSON string containing any payload properties not present in the schema"
  }

  dimension: app_version_major {
    sql: ${TABLE}.app_version_major ;;
    type: number
    suggest_persist_for: "24 hours"
  }

  dimension: app_version_minor {
    sql: ${TABLE}.app_version_minor ;;
    type: number
    suggest_persist_for: "24 hours"
  }

  dimension: app_version_patch {
    sql: ${TABLE}.app_version_patch ;;
    type: number
    suggest_persist_for: "24 hours"
  }

  dimension: client_info__android_sdk_version {
    sql: ${TABLE}.client_info.android_sdk_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Android SDK Version"
    description: "The optional Android specific SDK version of the software running on this hardware device."
  }

  dimension: client_info__app_build {
    sql: ${TABLE}.client_info.app_build ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "App Build"
    description: "The build identifier generated by the CI system (e.g. \"1234/A\"). For language bindings that provide automatic detection for this value, (e.g. Android/Kotlin), in the unlikely event that the build identifier can not be retrieved from the OS, it is set to \"inaccessible\". For other language bindings, if the value was not provided through configuration, this metric gets set to `Unknown`."
  }

  dimension: client_info__app_channel {
    sql: ${TABLE}.client_info.app_channel ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "App Channel"
    description: "The channel the application is being distributed on."
  }

  dimension: client_info__app_display_version {
    sql: ${TABLE}.client_info.app_display_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "App Display Version"
    description: "The user visible version string (e.g. \"1.0.3\").  In the unlikely event that the display version can not be retrieved, it is set to \"inaccessible\"."
  }

  dimension: client_info__architecture {
    sql: ${TABLE}.client_info.architecture ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Architecture"
    description: "The architecture of the device, (e.g. \"arm\", \"x86\")."
  }

  dimension: client_info__attribution__campaign {
    sql: ${TABLE}.client_info.attribution.campaign ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Attribution"
    group_item_label: "Campaign"
    description: "The attribution campaign (e.g. 'mozilla-org')."
  }

  dimension: client_info__attribution__content {
    sql: ${TABLE}.client_info.attribution.content ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Attribution"
    group_item_label: "Content"
    description: "The attribution content (e.g. 'firefoxview')."
  }

  dimension: client_info__attribution__ext {
    sql: ${TABLE}.client_info.attribution.ext ;;
    hidden: yes
  }

  dimension: client_info__attribution__medium {
    sql: ${TABLE}.client_info.attribution.medium ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Attribution"
    group_item_label: "Medium"
    description: "The attribution medium (e.g. 'organic' for a search engine)."
  }

  dimension: client_info__attribution__source {
    sql: ${TABLE}.client_info.attribution.source ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Attribution"
    group_item_label: "Source"
    description: "The attribution source (e.g. 'google-play')."
  }

  dimension: client_info__attribution__term {
    sql: ${TABLE}.client_info.attribution.term ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Attribution"
    group_item_label: "Term"
    description: "The attribution term (e.g. 'browser with developer tools for android')."
  }

  dimension: client_info__build_date {
    sql: ${TABLE}.client_info.build_date ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Build Date"
    description: "The date & time the application was built"
  }

  dimension: client_info__client_id {
    sql: ${TABLE}.client_info.client_id ;;
    hidden: yes
    description: "A UUID uniquely identifying the client."
  }

  dimension: client_info__device_manufacturer {
    sql: ${TABLE}.client_info.device_manufacturer ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Device Manufacturer"
    description: "The manufacturer of the device the application is running on. Not set if the device manufacturer can't be determined (e.g. on Desktop)."
  }

  dimension: client_info__device_model {
    sql: ${TABLE}.client_info.device_model ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Device Model"
    description: "The model of the device the application is running on. On Android, this is Build.MODEL, the user-visible marketing name, like \"Pixel 2 XL\". Not set if the device model can't be determined (e.g. on Desktop)."
  }

  dimension: client_info__distribution__ext {
    sql: ${TABLE}.client_info.distribution.ext ;;
    hidden: yes
  }

  dimension: client_info__distribution__name {
    sql: ${TABLE}.client_info.distribution.name ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info: Distribution"
    group_item_label: "Name"
    description: "The distribution name (e.g. 'MozillaOnline')."
  }

  dimension: client_info__first_run_date {
    sql: ${TABLE}.client_info.first_run_date ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "First Run Date"
    description: "The date of the first run of the application."
  }

  dimension: client_info__locale {
    sql: ${TABLE}.client_info.locale ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Locale"
    description: "The locale of the application during initialization (e.g. \"es-ES\"). If the locale can't be determined on the system, the value is [\"und\"](https://unicode.org/reports/tr35/#Unknown_or_Invalid_Identifiers), to indicate \"undetermined\"."
  }

  dimension: client_info__os {
    sql: ${TABLE}.client_info.os ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "OS"
    description: "The name of the operating system. Possible values: Android, iOS, Linux, Darwin, Windows, FreeBSD, NetBSD, OpenBSD, Solaris, unknown"
  }

  dimension: client_info__os_version {
    sql: ${TABLE}.client_info.os_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "OS Version"
    description: "The user-visible version of the operating system (e.g. \"1.2.3\"). If the version detection fails, this metric gets set to `Unknown`."
  }

  dimension: client_info__session_count {
    sql: ${TABLE}.client_info.session_count ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Session Count"
    description: "An optional running counter of the number of sessions for a client."
  }

  dimension: client_info__session_id {
    sql: ${TABLE}.client_info.session_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Session ID"
    description: "An optional UUID uniquely identifying the client's current session."
  }

  dimension: client_info__telemetry_sdk_build {
    sql: ${TABLE}.client_info.telemetry_sdk_build ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Telemetry SDK Build"
    description: "The version of the Glean SDK"
  }

  dimension: client_info__windows_build_number {
    sql: ${TABLE}.client_info.windows_build_number ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Client Info"
    group_item_label: "Windows Build Number"
    description: "The optional Windows build number, reported by Windows (e.g. 22000) and not set for other platforms"
  }

  dimension: document_id {
    sql: ${TABLE}.document_id ;;
    hidden: yes
    description: "The document ID specified in the URI when the client sent this message"
  }

  dimension: events {
    sql: ${TABLE}.events ;;
    hidden: yes
  }

  dimension: is_bot_generated {
    sql: ${TABLE}.is_bot_generated ;;
    type: yesno
    suggest_persist_for: "24 hours"
  }

  dimension: metadata__geo__city {
    sql: ${TABLE}.metadata.geo.city ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Geo"
    group_item_label: "City"
  }

  dimension: metadata__geo__country {
    sql: ${TABLE}.metadata.geo.country ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Geo"
    group_item_label: "Country"
    map_layer_name: countries
    description: "An ISO 3166-1 alpha-2 country code"
  }

  dimension: metadata__geo__db_version {
    sql: ${TABLE}.metadata.geo.db_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Geo"
    group_item_label: "DB Version"
    description: "The specific geo database version used for this lookup"
  }

  dimension: metadata__geo__subdivision1 {
    sql: ${TABLE}.metadata.geo.subdivision1 ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Geo"
    group_item_label: "Subdivision1"
    description: "First major country subdivision, typically a state, province, or county"
  }

  dimension: metadata__geo__subdivision2 {
    sql: ${TABLE}.metadata.geo.subdivision2 ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Geo"
    group_item_label: "Subdivision2"
    description: "Second major country subdivision; not applicable for most countries"
  }

  dimension: metadata__header__date {
    sql: ${TABLE}.metadata.header.date ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "Date"
    description: "Date HTTP header"
  }

  dimension: metadata__header__dnt {
    sql: ${TABLE}.metadata.header.dnt ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "DNT"
    description: "DNT (Do Not Track) HTTP header"
  }

  dimension: metadata__header__parsed_x_lb_tags__tls_cipher_hex {
    sql: ${TABLE}.metadata.header.parsed_x_lb_tags.tls_cipher_hex ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header: Parsed X LB Tags"
    group_item_label: "TLS Cipher Hex"
  }

  dimension: metadata__header__parsed_x_lb_tags__tls_version {
    sql: ${TABLE}.metadata.header.parsed_x_lb_tags.tls_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header: Parsed X LB Tags"
    group_item_label: "TLS Version"
  }

  dimension: metadata__header__parsed_x_source_tags {
    sql: ${TABLE}.metadata.header.parsed_x_source_tags ;;
    hidden: yes
  }

  dimension: metadata__header__x_debug_id {
    sql: ${TABLE}.metadata.header.x_debug_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X Debug ID"
    description: "X-Debug-Id HTTP header"
  }

  dimension: metadata__header__x_foxsec_ip_reputation {
    sql: ${TABLE}.metadata.header.x_foxsec_ip_reputation ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X Foxsec IP Reputation"
    description: "X-Foxsec-IP-Reputation header"
  }

  dimension: metadata__header__x_lb_tags {
    sql: ${TABLE}.metadata.header.x_lb_tags ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X LB Tags"
    description: "X-LB-Tags HTTP header"
  }

  dimension: metadata__header__x_pingsender_version {
    sql: ${TABLE}.metadata.header.x_pingsender_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X Pingsender Version"
    description: "X-PingSender-Version HTTP header"
  }

  dimension: metadata__header__x_source_tags {
    sql: ${TABLE}.metadata.header.x_source_tags ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X Source Tags"
    description: "X-Source-Tags HTTP header"
  }

  dimension: metadata__header__x_telemetry_agent {
    sql: ${TABLE}.metadata.header.x_telemetry_agent ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: Header"
    group_item_label: "X Telemetry Agent"
    description: "X-Telemetry-Agent HTTP header"
  }

  dimension: metadata__isp__db_version {
    sql: ${TABLE}.metadata.isp.db_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: ISP"
    group_item_label: "DB Version"
    description: "The specific geo ISP database version used for this lookup"
  }

  dimension: metadata__isp__name {
    sql: ${TABLE}.metadata.isp.name ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: ISP"
    group_item_label: "Name"
    description: "The name of the ISP associated with the client's IP address"
  }

  dimension: metadata__isp__organization {
    sql: ${TABLE}.metadata.isp.organization ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: ISP"
    group_item_label: "Organization"
    description: "The name of a specific business entity associated with the client's IP address when available; otherwise the ISP name"
  }

  dimension: metadata__user_agent__browser {
    sql: ${TABLE}.metadata.user_agent.browser ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: User Agent"
    group_item_label: "Browser"
  }

  dimension: metadata__user_agent__os {
    sql: ${TABLE}.metadata.user_agent.os ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: User Agent"
    group_item_label: "OS"
  }

  dimension: metadata__user_agent__version {
    sql: ${TABLE}.metadata.user_agent.version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metadata: User Agent"
    group_item_label: "Version"
  }

  dimension: metrics__boolean__system_has_win_package_id {
    sql: ${TABLE}.metrics.boolean.system_has_win_package_id ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "System Has Win Package ID"
    description: "Whether the app has a package identity.
Windows only.
"
  }

  dimension: metrics__boolean__system_is_wow_64 {
    sql: ${TABLE}.metrics.boolean.system_is_wow_64 ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "System Is Wow 64"
    description: "Whether we're in Windows32-on-Windows64 mode.
Windows only.
"
  }

  dimension: metrics__boolean__system_is_wow_arm_64 {
    sql: ${TABLE}.metrics.boolean.system_is_wow_arm_64 ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "System Is Wow Arm 64"
    description: "Whether we're in Windows32-on-WindowsForArm64 mode.
Windows only.
"
  }

  dimension: metrics__boolean__update_settings_auto_download {
    sql: ${TABLE}.metrics.boolean.update_settings_auto_download ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "Update Settings Auto Download"
    description: "Whether app updates are set to auto-download.
"
  }

  dimension: metrics__boolean__update_settings_background {
    sql: ${TABLE}.metrics.boolean.update_settings_background ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "Update Settings Background"
    description: "Whether updates can be delivered in the background.
"
  }

  dimension: metrics__boolean__update_settings_enabled {
    sql: ${TABLE}.metrics.boolean.update_settings_enabled ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "Update Settings Enabled"
    description: "Whether updates are available.
"
  }

  dimension: metrics__boolean__updater_available {
    sql: ${TABLE}.metrics.boolean.updater_available ;;
    type: yesno
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Boolean"
    group_item_label: "Updater Available"
    description: "Whether the app was built with the updater binary.
Corresponds to the value of the `MOZ_UPDATER` define.
"
  }

  dimension: metrics__labeled_counter__glean_error_invalid_label {
    sql: ${TABLE}.metrics.labeled_counter.glean_error_invalid_label ;;
    hidden: yes
    description: "Counts the number of times a metric was set with an invalid label.
The labels are the `category.name` identifier of the metric.
"
  }

  dimension: metrics__labeled_counter__glean_error_invalid_overflow {
    sql: ${TABLE}.metrics.labeled_counter.glean_error_invalid_overflow ;;
    hidden: yes
    description: "Counts the number of times a metric was set a value that overflowed.
The labels are the `category.name` identifier of the metric.
"
  }

  dimension: metrics__labeled_counter__glean_error_invalid_state {
    sql: ${TABLE}.metrics.labeled_counter.glean_error_invalid_state ;;
    hidden: yes
    description: "Counts the number of times a timing metric was used incorrectly.
The labels are the `category.name` identifier of the metric.
"
  }

  dimension: metrics__labeled_counter__glean_error_invalid_value {
    sql: ${TABLE}.metrics.labeled_counter.glean_error_invalid_value ;;
    hidden: yes
    description: "Counts the number of times a metric was set to an invalid value.
The labels are the `category.name` identifier of the metric.
"
  }

  dimension: metrics__object__glean_attribution_ext {
    sql: ${TABLE}.metrics.object.glean_attribution_ext ;;
    hidden: yes
    description: "Extended attribution information.
Mapped to client_info.attribution.ext in datasets.
* `experiment`: name/id of the enrolled funnel experiment
* `variation`: name/id of the variation cohort used in the enrolled funnel experiment
* `ua`: identifier derived from the user agent downloading the installer
        e.g. chrome, Google Chrome 123
* `dltoken`: Unique token created at Firefox download time.
             e.g. c18f86a3-f228-4d98-91bb-f90135c0aa9c
* `msstoresignedin`: only present if the installation was done through the Microsoft Store,
                     and was able to retrieve the \"campaign ID\" it was first installed with.
                     This value is \"true\" if the user was signed into the Microsoft Store
                     when they first installed, and false otherwise.
* `msclkid`: only present if the installation was done through the Microsoft Store, and the
             install is attributable to a Microsoft Store Ads Campaign ID. This differs
             from a Campaign ID originating "
  }

  dimension: metrics__object__glean_distribution_ext {
    sql: ${TABLE}.metrics.object.glean_distribution_ext ;;
    hidden: yes
    description: "Extended distribution information.
Mapped to client_info.distribution.ext in datasets.
* `distributionVersion`: pref `distribution.version`, `null` on failure
* `partnerId`: pref `mozilla.partner.id`, `null` on failure
* `distributor`:  pref `app.distributor`, `null` on failure
* `distributorChannel`: pref `app.distributor.channel`, `null` on failure
* `partnerNames`: list from prefs `app.partner.<name>=<name>`
"
  }

  dimension: metrics__object__hdd_binary {
    sql: ${TABLE}.metrics.object.hdd_binary ;;
    hidden: yes
    description: "Information about the disk the application binary is stored on.
Windows only.
* model - The disk's self-reported model string
* revision - The disk's self-reported revision string
* diskType - Either \"HDD\" or \"SSD\"
"
  }

  dimension: metrics__object__hdd_profile {
    sql: ${TABLE}.metrics.object.hdd_profile ;;
    hidden: yes
    description: "Information about the disk the profile is stored on.
Windows only.
* model - The disk's self-reported model string
* revision - The disk's self-reported revision string
* diskType - Either \"HDD\" or \"SSD\"
"
  }

  dimension: metrics__object__hdd_system {
    sql: ${TABLE}.metrics.object.hdd_system ;;
    hidden: yes
    description: "Information about the disk the system files are stored on.
Windows only.
* model - The disk's self-reported model string
* revision - The disk's self-reported revision string
* diskType - Either \"HDD\" or \"SSD\"
"
  }

  dimension: metrics__object__preferences_user_prefs {
    sql: ${TABLE}.metrics.object.preferences_user_prefs ;;
    hidden: yes
    description: "The fossilized remains of the Legacy Telemetry Environment's
`settings.userPrefs` structure.
A list of pref names and values.
Some values will be the string \"<user-set>\" to obscure the value.
Do not add more prefs to this list.
Prefer instead to instrument your prefs directly with individual metrics.
See Environment.sys.mjs' `DEFAULT_ENVIRONMENT_PREFS`.
"
  }

  dimension: metrics__quantity__profiles_creation_date {
    sql: ${TABLE}.metrics.quantity.profiles_creation_date ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "Profiles Creation Date"
    description: "The day the profile was created,
as determined by checking various file metadata in the profile directory.
Not considered to be particularly reliable in practice.
Prefer `client_info.first_run_date` in most cases.
e.g. 16446
"
  }

  dimension: metrics__quantity__profiles_first_use_date {
    sql: ${TABLE}.metrics.quantity.profiles_first_use_date ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "Profiles First Use Date"
    description: "Optional.
The day the profile was first used,
as determined by noticing that `times.json` wasn't present.
Prefer `client_info.first_run_date` in most cases.
e.g. 16446
"
  }

  dimension: metrics__quantity__profiles_recovered_from_backup {
    sql: ${TABLE}.metrics.quantity.profiles_recovered_from_backup ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "Profiles Recovered From Backup"
    description: "Optional.
The day the profile was recovered from backup,
persisted in `times.json`.
e.g. 16446
"
  }

  dimension: metrics__quantity__profiles_reset_date {
    sql: ${TABLE}.metrics.quantity.profiles_reset_date ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "Profiles Reset Date"
    description: "Optional.
The day the profile was most recently reset,
persisted in `times.json`.
e.g. 16446
"
  }

  dimension: metrics__quantity__system_cpu_big_cores {
    sql: ${TABLE}.metrics.quantity.system_cpu_big_cores ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Big Cores"
    description: "Big (or Performance) CPU cores.
"
  }

  dimension: metrics__quantity__system_cpu_family {
    sql: ${TABLE}.metrics.quantity.system_cpu_family ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Family"
    description: "CPU family.
"
  }

  dimension: metrics__quantity__system_cpu_l2_cache {
    sql: ${TABLE}.metrics.quantity.system_cpu_l2_cache ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU L2 Cache"
    description: "L2 cache size (only on Windows and Mac).
"
  }

  dimension: metrics__quantity__system_cpu_l3_cache {
    sql: ${TABLE}.metrics.quantity.system_cpu_l3_cache ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU L3 Cache"
    description: "L3 cache size.
"
  }

  dimension: metrics__quantity__system_cpu_little_cores {
    sql: ${TABLE}.metrics.quantity.system_cpu_little_cores ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Little Cores"
    description: "Little (or Efficient) CPU cores.
"
  }

  dimension: metrics__quantity__system_cpu_logical_cores {
    sql: ${TABLE}.metrics.quantity.system_cpu_logical_cores ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Logical Cores"
    description: "Logical CPU cores.
"
  }

  dimension: metrics__quantity__system_cpu_medium_cores {
    sql: ${TABLE}.metrics.quantity.system_cpu_medium_cores ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Medium Cores"
    description: "Medium CPU cores.
"
  }

  dimension: metrics__quantity__system_cpu_model {
    sql: ${TABLE}.metrics.quantity.system_cpu_model ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Model"
    description: "CPU model.
"
  }

  dimension: metrics__quantity__system_cpu_physical_cores {
    sql: ${TABLE}.metrics.quantity.system_cpu_physical_cores ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Physical Cores"
    description: "Physical CPU cores.
"
  }

  dimension: metrics__quantity__system_cpu_speed {
    sql: ${TABLE}.metrics.quantity.system_cpu_speed ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Speed"
    description: "CPU speed in MHz.
"
  }

  dimension: metrics__quantity__system_cpu_stepping {
    sql: ${TABLE}.metrics.quantity.system_cpu_stepping ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System CPU Stepping"
    description: "CPU stepping.
"
  }

  dimension: metrics__quantity__system_memory {
    sql: ${TABLE}.metrics.quantity.system_memory ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System Memory"
    description: "The physical memory size in MB (2^20 bytes).
e.g. 32211
"
  }

  dimension: metrics__quantity__system_os_service_pack_major {
    sql: ${TABLE}.metrics.quantity.system_os_service_pack_major ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System OS Service Pack Major"
    description: "The Windows service pack's major version, according to WindowsVersionInfo.
Windows only.
e.g. 0
"
  }

  dimension: metrics__quantity__system_os_service_pack_minor {
    sql: ${TABLE}.metrics.quantity.system_os_service_pack_minor ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System OS Service Pack Minor"
    description: "The Windows service pack's minor version, according to WindowsVersionInfo.
Windows only.
e.g. 0
"
  }

  dimension: metrics__quantity__system_os_windows_build_number {
    sql: ${TABLE}.metrics.quantity.system_os_windows_build_number ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System OS Windows Build Number"
    description: "The Windows build number, according to WindowsVersionInfo.
Windows only.
e.g. 26100
Expected in most cases to be identical to `client_info.windows_build_number`.
"
  }

  dimension: metrics__quantity__system_os_windows_ubr {
    sql: ${TABLE}.metrics.quantity.system_os_windows_ubr ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System OS Windows Ubr"
    description: "The Windows update build revision number, according to
`SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion`.
Windows only.
e.g. 3775
"
  }

  dimension: metrics__quantity__system_virtual_memory {
    sql: ${TABLE}.metrics.quantity.system_virtual_memory ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Metrics: Quantity"
    group_item_label: "System Virtual Memory"
    description: "The size of the user-mode portion of the virtual address space of the parent process.
Windows only.
e.g. 134217728
"
  }

  dimension: metrics__string__glean_client_annotation_experimentation_id {
    sql: ${TABLE}.metrics.string.glean_client_annotation_experimentation_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Glean Client Annotation Experimentation ID"
    description: "An experimentation identifier derived and provided by the application
for the purpose of experimentation enrollment.
"
  }

  dimension: metrics__string__system_cpu_name {
    sql: ${TABLE}.metrics.string.system_cpu_name ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System CPU Name"
    description: "The user readable CPU name. (e.g. \"Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz\")
"
  }

  dimension: metrics__string__system_cpu_vendor {
    sql: ${TABLE}.metrics.string.system_cpu_vendor ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System CPU Vendor"
    description: "The CPU vendor (e.g. \"GenuineIntel\").
"
  }

  dimension: metrics__string__system_os_distro {
    sql: ${TABLE}.metrics.string.system_os_distro ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Distro"
    description: "The Operating System's distribution, according to sysinfo.
Linux only.
e.g. \"Linuxmint\"
"
  }

  dimension: metrics__string__system_os_distro_version {
    sql: ${TABLE}.metrics.string.system_os_distro_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Distro Version"
    description: "The Operating System's distribution's version, according to sysinfo.
Linux only.
e.g. \"22\"
"
  }

  dimension: metrics__string__system_os_libstdcxx_version {
    sql: ${TABLE}.metrics.string.system_os_libstdcxx_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Libstdcxx Version"
    description: "The Operating System's libstdc++ highest GLIBCXX version.
Linux only.
e.g. \"3.4.33\"
"
  }

  dimension: metrics__string__system_os_locale {
    sql: ${TABLE}.metrics.string.system_os_locale ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Locale"
    description: "The Operating System's local, according to ospreferences.
e.g. \"en-US\"
"
  }

  dimension: metrics__string__system_os_name {
    sql: ${TABLE}.metrics.string.system_os_name ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Name"
    description: "The Operating System's name, according to sysinfo.
e.g. \"Windows_NT\"
Expected in most cases to be identical to `client_info.os`.
"
  }

  dimension: metrics__string__system_os_version {
    sql: ${TABLE}.metrics.string.system_os_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System OS Version"
    description: "The Operating System's version, according to sysinfo.
e.g. \"6.3\"
Expected in most cases to be identical to `client_info.os_version`.
"
  }

  dimension: metrics__string__system_win_package_family_name {
    sql: ${TABLE}.metrics.string.system_win_package_family_name ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "System Win Package Family Name"
    description: "The full application package name without any of the components that might change
during the life cycle of the app (such as the version number or the architecture).
Uniquely identifies the application within one Windows installation.
Windows only.
Only included if it begins with \"Mozilla.\" or \"MozillaCorporation.\".
e.g. \"Mozilla.Firefox_n80bbvh6b1yt2\"
"
  }

  dimension: metrics__string__update_previous_build_id {
    sql: ${TABLE}.metrics.string.update_previous_build_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Previous Build ID"
    description: "The Firefox build id the browser is updating from.
Follows the same format as application.buildId.
Only valid for \"update\" pings with reason \"success\".
"
  }

  dimension: metrics__string__update_previous_channel {
    sql: ${TABLE}.metrics.string.update_previous_channel ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Previous Channel"
    description: "The Firefox channel the profile was on before the update was applied.
Only valid for \"update\" pings with reason \"success\".
"
  }

  dimension: metrics__string__update_previous_version {
    sql: ${TABLE}.metrics.string.update_previous_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Previous Version"
    description: "The Firefox version the browser is updating from.
Follows the same format as application.version.
Only valid for \"update\" pings with reason \"success\".
"
  }

  dimension: metrics__string__update_settings_channel {
    sql: ${TABLE}.metrics.string.update_settings_channel ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Settings Channel"
    description: "The update channel according to defaults,
including partner bits.
e.g. \"nightly-cck\"
"
  }

  dimension: metrics__string__update_target_build_id {
    sql: ${TABLE}.metrics.string.update_target_build_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Target Build ID"
    description: "The Firefox build id the browser is updating to.
Follows the same format as application.buildId.
Only valid for \"update\" pings with reason \"ready\".
"
  }

  dimension: metrics__string__update_target_channel {
    sql: ${TABLE}.metrics.string.update_target_channel ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Target Channel"
    description: "The Firefox channel the update was fetched from.
Only valid for \"update\" pings with reason \"ready\".
"
  }

  dimension: metrics__string__update_target_display_version {
    sql: ${TABLE}.metrics.string.update_target_display_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Target Display Version"
    description: "The Firefox display version the browser is updating to.
This may contain a different value than `update.target_version`,
e.g. for the Beta channel this field will report the beta suffix
while `update.target_version` will only report the version number.
Only valid for \"update\" pings with reason \"ready\".
"
  }

  dimension: metrics__string__update_target_version {
    sql: ${TABLE}.metrics.string.update_target_version ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Update Target Version"
    description: "The Firefox version the browser is updating to.
Follows the same format as application.version.
Only valid for \"update\" pings with reason \"ready\".
"
  }

  dimension: metrics__string__xpcom_abi {
    sql: ${TABLE}.metrics.string.xpcom_abi ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Metrics: String"
    group_item_label: "Xpcom Abi"
    description: "A string tag identifying the binary ABI of the current processor and
compiler vtable. This is taken from the TARGET_XPCOM_ABI configure
variable. It may not be available on all platforms, especially
unusual processor or compiler combinations.

The result takes the form <processor>-<compilerABI>, for example:
  - x86-msvc
  - ppc-gcc3

This value should almost always be used in combination with the
operating system.
"
  }

  dimension: metrics__string_list__glean_ping_uploader_capabilities {
    sql: ${TABLE}.metrics.string_list.glean_ping_uploader_capabilities ;;
    hidden: yes
    description: "The list of requested uploader capabilities for the ping this is sent in.
Should be the same as the ones defined for that particular ping.

This metric is only attached to a ping if it already contains other data.
"
  }

  dimension: metrics__string_list__system_cpu_extensions {
    sql: ${TABLE}.metrics.string_list.system_cpu_extensions ;;
    hidden: yes
    description: "Recognized CPU extensions.
"
  }

  dimension: normalized_app_name {
    sql: ${TABLE}.normalized_app_name ;;
    type: string
    suggest_persist_for: "24 hours"
    description: "Set to \"Other\" if this message contained an unrecognized app name"
  }

  dimension: normalized_channel {
    sql: ${TABLE}.normalized_channel ;;
    type: string
    suggest_persist_for: "24 hours"
    description: "Set to \"Other\" if this message contained an unrecognized channel name"
  }

  dimension: normalized_country_code {
    sql: ${TABLE}.normalized_country_code ;;
    type: string
    suggest_persist_for: "24 hours"
    description: "An ISO 3166-1 alpha-2 country code"
  }

  dimension: normalized_os {
    sql: ${TABLE}.normalized_os ;;
    type: string
    suggest_persist_for: "24 hours"
    description: "Set to \"Other\" if this message contained an unrecognized OS name"
  }

  dimension: normalized_os_version {
    sql: ${TABLE}.normalized_os_version ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: ping_info__end_time {
    sql: ${TABLE}.ping_info.end_time ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Ping Info"
    group_item_label: "End Time"
  }

  dimension: ping_info__experiments {
    sql: ${TABLE}.ping_info.experiments ;;
    hidden: yes
  }

  dimension: ping_info__ping_type {
    sql: ${TABLE}.ping_info.ping_type ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Ping Info"
    group_item_label: "Ping Type"
  }

  dimension: ping_info__reason {
    sql: ${TABLE}.ping_info.reason ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Ping Info"
    group_item_label: "Reason"
  }

  dimension: ping_info__seq {
    sql: ${TABLE}.ping_info.seq ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Ping Info"
    group_item_label: "Seq"
  }

  dimension: ping_info__server_knobs_config__event_threshold {
    sql: ${TABLE}.ping_info.server_knobs_config.event_threshold ;;
    type: number
    suggest_persist_for: "24 hours"
    group_label: "Ping Info: Server Knobs Config"
    group_item_label: "Event Threshold"
    description: "Optional threshold for event buffering before an events ping is collected and submitted"
  }

  dimension: ping_info__server_knobs_config__metrics_enabled {
    sql: ${TABLE}.ping_info.server_knobs_config.metrics_enabled ;;
    hidden: yes
    description: "Map of metric identifiers (category.name) to boolean values indicating whether the metric is enabled"
  }

  dimension: ping_info__server_knobs_config__pings_enabled {
    sql: ${TABLE}.ping_info.server_knobs_config.pings_enabled ;;
    hidden: yes
    description: "Map of ping names to boolean values indicating whether the ping is enabled"
  }

  dimension: ping_info__start_time {
    sql: ${TABLE}.ping_info.start_time ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Ping Info"
    group_item_label: "Start Time"
  }

  dimension: sample_id {
    sql: ${TABLE}.sample_id ;;
    type: number
    suggest_persist_for: "24 hours"
    description: "Hashed version of client_id (if present) useful for partitioning; ranges from 0 to 99"
  }

  dimension_group: metadata__header__parsed {
    sql: ${TABLE}.metadata.header.parsed_date ;;
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year,
    ]
    label: "Metadata: Header: Parsed Date"
  }

  dimension_group: ping_info__parsed_end {
    sql: ${TABLE}.ping_info.parsed_end_time ;;
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year,
    ]
    label: "Ping Info: Parsed End Time"
  }

  dimension_group: ping_info__parsed_start {
    sql: ${TABLE}.ping_info.parsed_start_time ;;
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year,
    ]
    label: "Ping Info: Parsed Start Time"
  }

  dimension_group: submission {
    sql: ${TABLE}.submission_timestamp ;;
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year,
    ]
    description: "Time when the ingestion edge server accepted this message"
  }

  sql_table_name: `mozdata.firefox_desktop.update` ;;
}

view: update_table__events {
  dimension: category {
    sql: ${TABLE}.category ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: extra {
    sql: ${TABLE}.extra ;;
    hidden: yes
  }

  dimension: name {
    sql: ${TABLE}.name ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: timestamp {
    sql: ${TABLE}.timestamp ;;
    type: number
    suggest_persist_for: "24 hours"
  }
}

view: update_table__events__extra {
  dimension: key {
    sql: ${TABLE}.key ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: value {
    sql: ${TABLE}.value ;;
    type: string
    suggest_persist_for: "24 hours"
  }
}

view: update_table__ping_info__experiments {
  dimension: key {
    sql: ${TABLE}.key ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: value__branch {
    sql: ${TABLE}.value.branch ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Value"
    group_item_label: "Branch"
  }

  dimension: value__extra__enrollment_id {
    sql: ${TABLE}.value.extra.enrollment_id ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Value: Extra"
    group_item_label: "Enrollment ID"
  }

  dimension: value__extra__type {
    sql: ${TABLE}.value.extra.type ;;
    type: string
    suggest_persist_for: "24 hours"
    group_label: "Value: Extra"
    group_item_label: "Type"
  }
}

view: update_table__ping_info__server_knobs_config__metrics_enabled {
  dimension: key {
    sql: ${TABLE}.key ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: value {
    sql: ${TABLE}.value ;;
    type: yesno
    suggest_persist_for: "24 hours"
  }
}

view: update_table__ping_info__server_knobs_config__pings_enabled {
  dimension: key {
    sql: ${TABLE}.key ;;
    type: string
    suggest_persist_for: "24 hours"
  }

  dimension: value {
    sql: ${TABLE}.value ;;
    type: yesno
    suggest_persist_for: "24 hours"
  }
}