
# *Do not manually modify this file*
#
# This file has been generated via https://github.com/mozilla/lookml-generator
# You can extend this view in the looker-spoke-default project (https://github.com/mozilla/looker-spoke-default)

include: "/looker-hub/mozilla_vpn/views/main.view.lkml"
include: "/looker-hub/mozilla_vpn/datagroups/main_last_updated.datagroup.lkml"

explore: main {
  sql_always_where: ${main.submission_date} >= '2010-01-01' ;;
  view_label: " Main"
  description: "Explore for the main ping. A simple ping to send glean events generated by the Mozilla Cuddlefish apps."
  view_name: main

  join: main__metrics__labeled_counter__glean_error_invalid_label {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.metrics__labeled_counter__glean_error_invalid_label}) AS main__metrics__labeled_counter__glean_error_invalid_label ON ${main.document_id} = ${main__metrics__labeled_counter__glean_error_invalid_label.document_id} ;;
  }

  join: main__metrics__labeled_counter__glean_error_invalid_overflow {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.metrics__labeled_counter__glean_error_invalid_overflow}) AS main__metrics__labeled_counter__glean_error_invalid_overflow ON ${main.document_id} = ${main__metrics__labeled_counter__glean_error_invalid_overflow.document_id} ;;
  }

  join: main__metrics__labeled_counter__glean_error_invalid_state {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.metrics__labeled_counter__glean_error_invalid_state}) AS main__metrics__labeled_counter__glean_error_invalid_state ON ${main.document_id} = ${main__metrics__labeled_counter__glean_error_invalid_state.document_id} ;;
  }

  join: main__metrics__labeled_counter__glean_error_invalid_value {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.metrics__labeled_counter__glean_error_invalid_value}) AS main__metrics__labeled_counter__glean_error_invalid_value ON ${main.document_id} = ${main__metrics__labeled_counter__glean_error_invalid_value.document_id} ;;
  }

  join: main__events {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.events}) AS main__events ;;
  }

  join: main__events__extra {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main__events.extra}) AS main__events__extra ;;
  }

  join: main__ping_info__experiments {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.ping_info__experiments}) AS main__ping_info__experiments ;;
  }

  join: main__ping_info__server_knobs_config__metrics_enabled {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.ping_info__server_knobs_config__metrics_enabled}) AS main__ping_info__server_knobs_config__metrics_enabled ;;
  }

  join: main__ping_info__server_knobs_config__pings_enabled {
    relationship: one_to_many
    sql: LEFT JOIN UNNEST(${main.ping_info__server_knobs_config__pings_enabled}) AS main__ping_info__server_knobs_config__pings_enabled ;;
  }

  persist_with: main_last_updated

  always_filter: {
    filters: [
      submission_date: "28 days",
    ]
  }
}